# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "selenium-webdriver", "~> 3.141"

gem "minitest", "~> 5.11"
