require 'rubygems'
require 'rake/testtask'
require 'parallel'
require 'json'

@browsers = JSON.parse(File.read('browsers.json'))
@parallel_limit = (ENV['nodes'] || 5).to_i

task :minitest do
  current_browser = ''
  begin
    Parallel.map(@browsers, in_threads: @parallel_limit) do |capabilities|
      current_browser = capabilities
      puts "Running with: #{capabilities.inspect}"
      IO.popen(['ruby', 'parallel_minitest.rb', capabilities.to_json]) do |io|
        io.each do |line|
          puts line
        end
      end
    end
  rescue SystemExit, Interrupt
    puts 'User stopped script!'
    puts "Failed to run tests for #{current_browser.inspect}"
  end
end

task default: [:minitest]
