require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'
require 'parallel'
require 'json'

@browsers = JSON.load(open('browsers.sample.json'))
@parallel_limit = ENV["nodes"] || 1
@parallel_limit = @parallel_limit.to_i

task :cucumber do
  Parallel.map(@browsers, :in_processes => @parallel_limit) do |browser|
    begin
      puts "Running with: #{browser.inspect}"
      ENV['SELENIUM_BROWSER'] = browser['browser']
      ENV['SELENIUM_VERSION'] = browser['browser_version']
      ENV['BS_AUTOMATE_OS'] = browser['os']
      ENV['BS_AUTOMATE_OS_VERSION'] = browser['os_version']
      ENV['BS_AUTOMATE_PLATFORM'] = browser['platform']
      ENV['BS_AUTOMATE_DEVICE'] = browser['device']
      ENV['BS_AUTOMATE_BROWSER_NAME'] = browser['browserName']
      ENV['BS_AUTOMATE_PROJECT'] = browser['project']
      ENV['BS_AUTOMATE_BUILD'] = browser['build']

      Rake::Task[:run_features].execute()
    rescue RuntimeError => e
      puts "Error while running task"
    end
  end
end

Cucumber::Rake::Task.new(:run_features)
task :default => [:cucumber]
